site_name: Документация FeedbackGenerator
site_url: https://example.com # Не забыть поменять!!
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/favicon.svg
  icon:
    admonition:
      tip: octicons/light-bulb-24



  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer

    - search.suggest

    - content.code.copy
    - content.code.annotate



  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/brightness-4
        name: Включить светлую тему

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Включить тёмную тему

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Включить тему операционной системы
  font:
    text: Roboto
    code: Roboto Mono

  language: ru

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: "🔗"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist


extra_css:
  - assets/custom.css

extra_javascript:
  - assets/custom.js

plugins:
  - tags
  - search
  - awesome-nav
  - git-revision-date-localized:
      enable_creation_date: true
      locale: ru
      fallback_to_build_date: true
  - mermaid2
  - redirects
  - minify:
      minify_html: true

repo_url: https://github.com/BountyHanter/FeedbackGenerator
repo_name: FeedbackGenerator

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BountyHanter