# Generated by Django 5.1.1 on 2024-12-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_dgisprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgisprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
