# Generated by Django 5.1.1 on 2024-12-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_dgisprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dgisfilial',
            old_name='filial_id',
            new_name='dgis_filial_id',
        ),
    ]
