# Generated by Django 5.1.1 on 2025-02-28 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_rename_filial_id_dgisfilial_dgis_filial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisfilial',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgis_filials', to='main_site.dgisprofile'),
        ),
    ]
