# Generated by Django 5.1.1 on 2025-02-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_flampprofile_flampfilial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgisprofile',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='flampprofile',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
